[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "fake_membership_list"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/fake_membership_list" }
dependencies = [
    "attrs==24.2.0",
    "faker_education==1.2.1",
    "Faker==33.0.0",
    "mapbox==0.18.1",
    "numpy==2.1.3",
    "pandas==2.2.3",
    "python-dateutil==2.9.0.post0",
    "ratelimit==2.2.1",
    "tqdm==4.67.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit==4.0.1",
    "ruff==0.7.3"
]
github-actions = [
    "ruff==0.7.3",
    "ydiff==1.4.1"
]
