[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "fake_membership_list"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.9"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/fake_membership_list" }
dependencies = [
    "attrs==23.2.0",
    "faker_education==1.2.1",
    "Faker==22.6.0",
    "mapbox==0.18.1",
    "numpy==1.26.3",
    "pandas==2.2.0",
    "python-dateutil==2.8.2",
    "ratelimit==2.2.1",
    "tqdm==4.66.1",
]

[project.optional-dependencies]
dev = [
    "pre-commit==3.6.0",
    "ruff==0.2.1"
]
github-actions = [
    "ruff==0.2.1",
    "ydiff==1.2"
]
