[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "fake_membership_list"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.9"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/fake_membership_list" }
dependencies = [
    "attrs==23.2.0",
    "faker_education==1.2.1",
    "Faker==25.8.0",
    "mapbox==0.18.1",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "python-dateutil==2.9.0.post0",
    "ratelimit==2.2.1",
    "tqdm==4.66.4",
]

[project.optional-dependencies]
dev = [
    "pre-commit==3.7.1",
    "ruff==0.4.7"
]
github-actions = [
    "ruff==0.4.7",
    "ydiff==1.3"
]
